name: ireland_visa_checker
description: Check Irish visa application decisions across multiple embassies.
publish_to: 'none'
version: 1.1.0+13

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  intl: ^0.19.0
  url_launcher: ^6.3.0
  flutter_local_notifications: ^17.2.2
  workmanager: ^0.9.0
  share_plus: ^10.1.2
  home_widget: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
